"""followers

Revision ID: 054a171d6b24
Revises: 59965912077e
Create Date: 2018-11-09 14:47:17.376639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054a171d6b24'
down_revision = '59965912077e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
